name: "3 ecosystem install"

on:
  workflow_dispatch:
    inputs:
      SKIP_JAVASCRIPT:
        description: "Skip JavaScript"
        type: boolean
        default: false
  
      SKIP_GO:
        description: "Skip Go"
        type: boolean
        default: false

      SKIP_RUBY:
        description: "Skip Ruby"
        type: boolean
        default: false

permissions:
  checks: write
  actions: read
  contents: read
  id-token: write

jobs:
  build-javascript:
    if: ${{ inputs.SKIP_JAVASCRIPT != true }}
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          api_url: "https://app.stage.invisirisk.com"
          app_token: 7MGL3OurBJVSE8VrI_m-cJw5eUmtvLhpZu3gxSbeww-lMJX_JOdukvEOxDZsOpCBAe93Uk2vlao_pgitOjl28w
      # ============= InvisiRisk Setup End =============
      - uses: actions/checkout@v4
      - run: npm install --no-audit --no-fund
      - run: curl -sS --connect-timeout 5 --max-time 15 -o /dev/null "https://speed.hetzner.de/100MB.bin?d=$(echo hello | base64)" || true

      
  build-go:
    if: ${{ inputs.SKIP_GO != true }}
    runs-on: ubuntu-latest
    container:
      image: golang:1.22
    steps:    
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          api_url: "https://app.stage.invisirisk.com"
          app_token: 7MGL3OurBJVSE8VrI_m-cJw5eUmtvLhpZu3gxSbeww-lMJX_JOdukvEOxDZsOpCBAe93Uk2vlao_pgitOjl28w
      # ============= InvisiRisk Setup End =============
      - uses: actions/checkout@v4
      - run: go mod download -x
      - run: curl -sS --connect-timeout 5 --max-time 15 -o /dev/null "https://registry.npmjs.org/express/-/express-4.18.2.tgz" || true


  build-ruby:
    if: ${{ inputs.SKIP_RUBY != true }}
    runs-on: ubuntu-latest
    container:
      image: ruby:3.3
    steps: 
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          api_url: "https://app.stage.invisirisk.com"
          app_token: 7MGL3OurBJVSE8VrI_m-cJw5eUmtvLhpZu3gxSbeww-lMJX_JOdukvEOxDZsOpCBAe93Uk2vlao_pgitOjl28w
      # ============= InvisiRisk Setup End =============
      - uses: actions/checkout@v4
      - run: bundle install
      - run: curl -sS --connect-timeout 5 --max-time 15 -o /dev/null "https://proof.ovh.net/files/100Mb.dat" || true
